name: CSGO Docker

on: [push, pull_request]

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build-docker:
        name: Build CSGO Docker
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build
            run: ./buildimg.sh
