name: CSGO Docker

on: [push, pull_request]

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build-docker:

        runs-on: ubuntu-latest

        name: Build CSGO Docker

        steps:
        - uses: actions/checkout@v2

        - name: Build
          run: ./buildimg.sh

        - name: Run          
          timeout-minutes: 0.2
          run: docker run -p 27015:27015/udp cycom/csgo
