name: CSGO Docker

on: [push, pull_request]

defaults:
    run:
        shell: bash
        working-directory: .
        runs-on: ubuntu-latest

jobs:
    build-docker:
        name: Build CSGO Docker

        steps:
        - uses: actions/checkout@v2
        - name: Build
          run: ./buildimg.sh

    run-docker:
        name: Run CSGO Docker

        steps:
        - uses: actions/checkout@v2
        - name: Run
          command_timeout: 10s
          run: ./csgo 27015
