name: CSGO Docker

on:
    push:
        branches:
            - test

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build-docker:

        runs-on: ubuntu-latest

        name: Build CSGO Docker

        steps:
        - uses: actions/checkout@v2

        - name: Build
          run: ./buildimg

    merge-branch:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master

          - name: Merge test into master
            uses: devmasx/merge-branch@v1.3.1
            with:
              type: now
              target_branch: master
              github_token: ${{ github.token }}
